- name: Pull Docker Container
  command:
    cmd: docker pull solr:8.8.1

- name: Run Docker Container
  command:
    cmd: docker run -d -p 8983:8983 --name solr881 -t solr:8.8.1
  ignore_errors: true
